### PR TITLE
Ptnfly 2147 alpha cleanup

### PR DESCRIPTION
**Pull request by andresgalante**
:volcano: I've move things around, change the names of the sass files, changed the spaces on tables and the color of the validation labels.

And it should all be here
http://blog.andresgalante.com/patternfly-atomic/

### CODE REVIEW

**Comment by srambach** [comment]
Do we still want the numbers on the breadcrumb files?

**Comment by andresgalante** [comment]
No, we don't 😄

**Comment by srambach** [comment]
Also, is there a general scheme for plural vs singular names? Do we care?

**Comment by andresgalante** [comment]
@srambach I'd say yes, not for this PR, and maybe not for alpha 1. Lets create a story to fix that and write guidelines.

**Comment by srambach** [comment]
OK! Everything LGTM then!

**Comment by jgiardino** [comment]
These updates look good to me, too!

**Pull request merged**
