### PR TITLE
Adds paginagtion, creates more spacing variables and introdces better namens

### PR DESCRIPTION
**Pull request by andresgalante**
@srambach @cshinn @jgiardino @bleathem Can you guys please review this one?
I've change the names of some files to better structure what we are showing.

I've also created the pagination components to test out the spacing variables. 

If you like this PR I recommend merging it before start working on the repo and follow the same naming conventions for the rest of the components.

Thanks a lot! 😄

### CODE REVIEW

**Comment by srambach** [comment]
You have button.mustache and 01-button-styles but 02-button**s**-sizes. Should it be 02-button-sizes.mustache instead?

**Comment by cshinn** [comment]
RE: button vs buttons, I think it makes more sense for us to refer to our basics in the singular

**Comment by andresgalante** [comment]
@cshinn @srambach thanks for the review, I've change the names

**Comment by srambach** [comment]
LGTM

**Comment by cshinn** [comment]
Looks good

**Comment by andresgalante** [comment]
Merge it! @cshinn do you have merge rights to this repo?

**Comment by cshinn** [comment]
Nope!

**Comment by andresgalante** [comment]
@cshinn congrats, you are now a core member of patternfly

**Pull request merged**
